name: free-programming-books-lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: echo asdf
    - run: npm install https://github.com/LeoOuyang24/free-programming-books-lint
    - run: npm ls
    - run: fpb-lint ./books/
    - run: fpb-lint ./casts/
    - run: fpb-lint ./courses/
    - run: fpb-lint ./more/

